/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BAccordion: typeof import('bootstrap-vue-next')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next')['BAccordionItem']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next')['BButtonGroup']
    BButtonToolbar: typeof import('bootstrap-vue-next')['BButtonToolbar']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next')['BFormCheckboxGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BInput: typeof import('bootstrap-vue-next')['BInput']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BListGroup: typeof import('bootstrap-vue-next')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    DirectionalShadow: typeof import('./src/components/common/DirectionalShadow.vue')['default']
    'LineMd:closeToMenuTransition': typeof import('~icons/line-md/close-to-menu-transition')['default']
    'LineMd:menuToCloseTransition': typeof import('~icons/line-md/menu-to-close-transition')['default']
    'LineMd:minus': typeof import('~icons/line-md/minus')['default']
    'LineMd:plus': typeof import('~icons/line-md/plus')['default']
    'LineMd:sunnyOutlineTwotone': typeof import('~icons/line-md/sunny-outline-twotone')['default']
    LoadingScreen: typeof import('./src/components/loaders/LoadingScreen.vue')['default']
    MenuToggle: typeof import('./src/components/common/MenuToggle.vue')['default']
    PublishedRoster: typeof import('./src/components/roster/PublishedRoster.vue')['default']
    Roster: typeof import('./src/components/roster/Roster.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TooltipItem: typeof import('./src/components/common/TooltipItem.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
