/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next')['BButtonGroup']
    BButtonToolbar: typeof import('bootstrap-vue-next')['BButtonToolbar']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next')['BFormCheckboxGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BInput: typeof import('bootstrap-vue-next')['BInput']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    DirectionalShadow: typeof import('./src/components/common/DirectionalShadow.vue')['default']
    GmailLogin: typeof import('./src/components/login/GmailLogin.vue')['default']
    'LineMd:arrowDown': typeof import('~icons/line-md/arrow-down')['default']
    'LineMd:calendar': typeof import('~icons/line-md/calendar')['default']
    'LineMd:checkList3Twotone': typeof import('~icons/line-md/check-list3-twotone')['default']
    'LineMd:clipboardArrow': typeof import('~icons/line-md/clipboard-arrow')['default']
    'LineMd:coffeeHalfEmptyTwotoneLoop': typeof import('~icons/line-md/coffee-half-empty-twotone-loop')['default']
    'LineMd:minus': typeof import('~icons/line-md/minus')['default']
    'LineMd:plus': typeof import('~icons/line-md/plus')['default']
    'LineMd:questionCircle': typeof import('~icons/line-md/question-circle')['default']
    'LineMd:sunnyOutlineTwotone': typeof import('~icons/line-md/sunny-outline-twotone')['default']
    LoadingScreen: typeof import('./src/components/loaders/LoadingScreen.vue')['default']
    MasterclassItem: typeof import('./src/components/masterclass/MasterclassItem.vue')['default']
    MenuTile: typeof import('./src/components/home/MenuTile.vue')['default']
    Roster: typeof import('./src/components/roster/Roster.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TooltipItem: typeof import('./src/components/common/TooltipItem.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
