/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CaseFile: typeof import('./src/components/game/CaseFile.vue')['default']
    CountdownSetter: typeof import('./src/components/game/CountdownSetter.vue')['default']
    CountdownTimer: typeof import('./src/components/game/CountdownTimer.vue')['default']
    DirectionalShadow: typeof import('./src/components/common/DirectionalShadow.vue')['default']
    ExpRoomCell: typeof import('./src/components/game/table/ExpRoomCell.vue')['default']
    GameAdmin: typeof import('./src/components/game/GameAdmin.vue')['default']
    GameAnswers: typeof import('./src/components/game/GameAnswers.vue')['default']
    GameMap1: typeof import('./src/components/game/GameMap1.vue')['default']
    GameMap2: typeof import('./src/components/game/GameMap2.vue')['default']
    GameRules: typeof import('./src/components/game/GameRules.vue')['default']
    InterviewVideos: typeof import('./src/components/game/InterviewVideos.vue')['default']
    'LineMd:account': typeof import('~icons/line-md/account')['default']
    'LineMd:arrowDown': typeof import('~icons/line-md/arrow-down')['default']
    'LineMd:arrowSmallLeft': typeof import('~icons/line-md/arrow-small-left')['default']
    'LineMd:arrowSmallRight': typeof import('~icons/line-md/arrow-small-right')['default']
    'LineMd:bellTwotone': typeof import('~icons/line-md/bell-twotone')['default']
    'LineMd:calendar': typeof import('~icons/line-md/calendar')['default']
    'LineMd:checkList3Twotone': typeof import('~icons/line-md/check-list3-twotone')['default']
    'LineMd:clipboardArrow': typeof import('~icons/line-md/clipboard-arrow')['default']
    'LineMd:coffeeHalfEmptyTwotoneLoop': typeof import('~icons/line-md/coffee-half-empty-twotone-loop')['default']
    'LineMd:downloadingLoop': typeof import('~icons/line-md/downloading-loop')['default']
    'LineMd:loadingAltLoop': typeof import('~icons/line-md/loading-alt-loop')['default']
    'LineMd:questionCircle': typeof import('~icons/line-md/question-circle')['default']
    'LineMd:searchTwotone': typeof import('~icons/line-md/search-twotone')['default']
    'LineMd:sunnyOutlineTwotone': typeof import('~icons/line-md/sunny-outline-twotone')['default']
    'LineMd:switchFilledToSwitchOffFilledTransition': typeof import('~icons/line-md/switch-filled-to-switch-off-filled-transition')['default']
    'LineMd:switchOffFilledToSwitchFilledTransition': typeof import('~icons/line-md/switch-off-filled-to-switch-filled-transition')['default']
    'LineMd:telegram': typeof import('~icons/line-md/telegram')['default']
    LoadingScreen: typeof import('./src/components/loaders/LoadingScreen.vue')['default']
    LoginButton: typeof import('./src/components/buttons/LoginButton.vue')['default']
    LogoutButton: typeof import('./src/components/settings/LogoutButton.vue')['default']
    MasterclassItem: typeof import('./src/components/masterclass/MasterclassItem.vue')['default']
    MenuTile: typeof import('./src/components/home/MenuTile.vue')['default']
    PoliceLine: typeof import('./src/components/game/PoliceLine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveSettingsButton: typeof import('./src/components/settings/SaveSettingsButton.vue')['default']
    SettingsToggle: typeof import('./src/components/settings/SettingsToggle.vue')['default']
    StationCell: typeof import('./src/components/game/table/StationCell.vue')['default']
    SubmitGameAnswer: typeof import('./src/components/game/SubmitGameAnswer.vue')['default']
    TelegramButtonLoader: typeof import('./src/components/loaders/TelegramButtonLoader.vue')['default']
    TooltipItem: typeof import('./src/components/common/TooltipItem.vue')['default']
    TrainingSchedule: typeof import('./src/components/game/TrainingSchedule.vue')['default']
    TrainingScheduleAdjuster: typeof import('./src/components/game/TrainingScheduleAdjuster.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
